[defaults]
vfat_defaults=uid=$UID,gid=$GID,shortname=mixed,umask=0077,utf8=1,flush,noexec,nosuid,nodev
exfat_defaults=uid=$UID,gid=$GID,noexec,nosuid,nodev
ntfs_defaults=uid=$UID,gid=$GID,windows_names,noexec,nosuid,nodev
ext4_defaults=noexec,nosuid,nodev
