#!/usr/bin/env bash
# get path to folder, to return to for copying configs
curr_dir="$(pwd)"

# install yay using a temporary directory
# only for arch systems
install_yay() {
    printf "##### Installing AUR helper YAY!\n"
    sudo pacman -S git base-devel
    yay_temp_dir=$(mktemp -d)
    cd "$yay_temp_dir"
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    makepage -si
    rm -drf "$yay_temp_dir"
    printf "##### YAY has been installed!\n"
}

# copy all config files in repo to user config folder
copy_configs() {
    printf "##### Copying config files!\n"
    cd "$curr_dir"
    cp -R "../.config/"* "~/.config/"
}

copy_shell_configs() {
    printf "##### Copying SHELL config files!\n"
    cd "$curr_dir"
    cp ../.zshrc ~
    cp ../.bashrc ~
}

copy_bin_folder () {
    printf "##### Copying bin folder!\n"
    cd "$curr_dir"
    cp ../.bin ~
}

# ask user for confirmation with custom prompt, continues if yes
confirm_action() {
    read -p "$1 [y/n] " -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        return
    else 
        exit 
    fi
}

printf "##### This will install all a lot of packages!\n"
confirm_action "##### Are you sure you want to continue?"
case $1 in
arch)
    # install all relevant arch packages
    sudo pacman -Syu
    install_yay
    yay -Sy \
    git \
    wget \
    base-devel \
    vim \
    neovim \
    kate \
    tmux \
    zsh \
    firefox \
    openssh \
    keepassxc \
    ufw \
    i3-wm \
    picom \
    rofi \
    dunst \
    polybar \
    rxvt-unicode \
    alacritty \
    ttf-ibm-plex
    ;;
   
debian)
    sudo apt update && apt upgrade
    sudo apt install 
    git \
    wget \
    vim \
    tmux \
    zsh \
    base-devel \
    firefox \
    vlc \
    openssh \
    keepassxc \
    ufw \
    picom \
    rofi \
    dunst \
    rxvt-unicode \
    thunderbird \
    alacritty \
    polybar \
    ttf-ibm-plex
    ;;

*)
    printf "Call script using \n\tbash desktop <debian | arch>\n"
    ;;
esac

printf "##### Copy .bin folder to user home? Will overwrite any existing ones!\n"
confirm_action "##### Are you sure you want to continue?"
copy_bin_folder

printf "##### Copy config files to user folder? Will overwrite any existing ones!\n"
confirm_action "##### Are you sure you want to continue?"
copy_configs

printf "##### Copy SHELL config files to user folder? Will overwrite any existing ones!\n"
printf "##### THIS MIGHT BREAK YOUR SYSTEM!\n"
confirm_action "##### Are you sure you want to continue?"
copy_shell_configs

printf "##### SETUP DONE"

printf "##### AFTER SETUP TASKS\n
\t - run install-plug-vim.sh in .config/nvim/autoload to install vim plugin manager\n
\t - run PlugInstall in neovim to install plugins afterwards\n
\t - optionally install starship for a better shell\n
\t - check .zshrc Source Plugins section to see which plugins to install\n"
