####################################################################################################
# SDDM Display Manager
####################################################################################################

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
# Set theme, themes can be found under /usr/share/sddm/themes/
Current=breeze

[Autologin]
# Automatically login again after exiting session
Relogin=false
# Session to choose for automatic login, e.g. KDE, Sway
Session=
# Username to automatically login as
User=

[Users]
# Limit range of UIDs SDDM will consider for users
MaximumUid=60513
MinimumUid=60513

# Dont remember the last user
RememberLastUser=false
