####################################################################################################
# Starship Shell Prompt
####################################################################################################

###########################################################################
# General
###########################################################################

# addinsert blank line between shell prompts
add_newline = false
palette = 'meitnerium'

###########################################################################
# palette meitnerium - custom meitnerium colors
###########################################################################

[palettes.meitnerium]
background = '#21262b'
foreground = '#dededd'
primary = '#dededd'
secondary = '#424b55'
red = '#f32e2e'
red-light = '#ff9f9f'
green = '#75ee37'
green-light = '#acff82'
yellow = '#f2cf26'
yellow-light = '#ffe87b'
blue = '#3160f2'
blue-light = '#7c9cff'
pink = '#c930f3'
pink-light = '#e279ff'
cyan = '#2beeb4'
cyan-light = '#75ffd6'

###########################################################################
# character - Characters besides text input
###########################################################################

[character]
disabled = false
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[--VIM](bold green)'
vimcmd_replace_one_symbol = '[--VIM-Repl](bold purple)'
vimcmd_replace_symbol = '[--VIM-Repl](bold purple)'
vimcmd_visual_symbol = '[--VIM-Vis](bold yellow)'

###########################################################################
# cmd_duration - Shows duration last command took to execute
###########################################################################

[cmd_duration]
disabled = true

###########################################################################
# directory - shows path to current directory
###########################################################################

[directory]
disabled = false
style = 'bold blue'
read_only = 'RO'
read_only_style = 'bold red'
format = '[($read_only! )]($read_only_style)[$path]($style) '
home_symbol = "home"
# number of parent folders to display
truncation_length = 5
truncation_symbol = '.../'
# truncate to root of repo
truncate_to_repo = false
use_os_path_sep = true

###########################################################################
# conda - Shows current conda environment
# Note: does NOT surpress condas prompt modifier! run `conda config --set changeps1 False` to
#       disable
###########################################################################

[conda]
disabled = false
symbol = 'CONDA'
style = 'bold green'
format = '[$symbol: $environment]($style)'
# ignore base module in prompt
ignore_base = true

###########################################################################
# conatiner - shows container name if inside a container
###########################################################################

[container]
disabled = false
symbol = 'CONTAINER'
style = 'bold blue'
format = '[$symbol: $environment]($style)'

###########################################################################
# docker_context - shows currently active docker context
###########################################################################

[docker_context]
disabled = false
symbol = 'DOCKER'
style = 'blue bold'
format = '[$symbol: $context]($style)'

###########################################################################
# nodejs - shows currently installed version of node.js
###########################################################################

[nodejs]
disabled = true

###########################################################################
# git_branch - shows current active branch
###########################################################################

[git_branch]
disabled = false
symbol = ''
style = 'bold purple'
format = 'on [$symbol$branch(:$remote_branch)]($style) '

###########################################################################
#  git_commit - shows current commit hash and tag
###########################################################################

[git_commit]
disabled = false
style = 'bold green'
format = '[\($hash$tag\)]($style) '

###########################################################################
# git_state - shows current state of git repo, e.g. rebasing, bisecting, reverting ...
###########################################################################

[git_state]
disabled = false

###########################################################################
# git_metrics - shows current deleted and added lines for git repo
###########################################################################

[git_metrics]
disabled = true

###########################################################################
# git_status - shows status of current git repo
###########################################################################

[git_status]
disabled = false
style = 'underline yellow'
format = '([\[$all_status\]]($style) )([$ahead_behind](yellow) )'

#list of statuses
conflicted = 'CONFLICTED '
#ahead = 'AHEAD '
#behind = 'BEHIND '
#diverged = 'DIVERGED '
up_to_date = 'UPTODATE '
untracked = 'UNTRACKED '
stashed = 'STASHED '
modified = 'MODIFIED '
staged = 'STAGED '
renamed = 'RENAMED '
deleted = 'DELELTED '

ahead = 'AHEAD: ${count}'
diverged = 'AHEAD: ${ahead_count} BEHIND:${behind_count}'
behind = 'BEHIND: ${count}'

###########################################################################
# golang - shows currently installed version of go
###########################################################################

[golang]
disabled = false

###########################################################################
# hostname - shows system hostname
###########################################################################

[hostname]
disabled = false
ssh_symbol = 'SSH'
style = 'underline yellow'
format = '[\[($ssh_symbol: )$hostname\]]($style)[:](white) '
ssh_only = false

###########################################################################
# line_break - splits prompt into two lines
###########################################################################

[line_break]
disabled = false

###########################################################################
# username - show active username
###########################################################################

[username]
disabled = false
style_user = 'underline green'
style_root = 'bold underline red'
format = '[\[$user\]]($style)@'
show_always = true

###########################################################################
# sudo - shows symbol if sudo credentials are currently cached
###########################################################################

[sudo]
disabled = false
symbol = 'SUDO'
style = 'bold underline red'
format = '[!$symbol!]($style)'

###########################################################################
# time - shows current local time
###########################################################################

[time]
disabled = false
style = 'bold white'
format = '[$time]($style) '
use_12hr = false
utc_time_offset = 'local'
time_format = '%T'
