#!/usr/bin/env bash
# batch rename files

operation="$1"
fileSearchPattern="$2"
fileReplacePattern="$3"

echo "----- Effected files: -----"

for file in $fileSearchPattern ; do
    case $operation in
        append)
            echo "$file -> ${file%$fileSearchPattern}$fileReplacePattern" 
            ;;
        prepend)
            echo "$file -> $fileReplacePattern${file}" 
            ;;
        remove)
            echo "$file -> ${file/$fileReplacePattern/}" 
            ;;
        *)
            echo "<append / prepend  / remove> <fileSearchPattern> <fileReplacePattern>"
            ;;
    esac
done

read -p "Confirm action: " -r
if [[ $REPLY =~ [Yy]$ ]]
then
    for file2 in $fileSearchPattern ; do
        case $operation in
        append)
            mv -v "$file2" "${file2%$fileSearchPattern}$fileReplacePattern"
            ;;
        prepend)
            mv -v "$file2" "$fileReplacePattern${file2}" 
            ;;
        remove)
            mv -v "$file2" "${file2/$fileReplacePattern/}" 
            ;;
        esac
    done
fi
