###########################################################################
# COLORS - Secret Theme
###########################################################################
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x4b5d87"
blue = "0xf074ba"
cyan = "0xadfffe"
green = "0x79d0bb"
magenta = "0xb38ff6"
red = "0xe29fa4"
white = "0xfefbec"
yellow = "0xf0d57f"

[colors.normal]
black = "0x253a6b"
blue = "0xff0180"
cyan = "0x6bd7d3"
green = "0x0bb981"
magenta = "0x8433fe"
red = "0xe45451"
white = "0x95917d"
yellow = "0xfcc212"

[colors.primary]
background = "0x0f172a"
foreground = "0xe1e7f5"
