###########################################################################
# COLORS - Secret Theme
###########################################################################
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#4b5d87"
blue = "#ABCDD9"
cyan = "#adfffe"
green = "#79d0bb"
magenta = "#b38ff6"
red = "#e29fa4"
white = "#fefbec"
yellow = "#f0d57f"

[colors.normal]
black = "#253a6b"
blue = "#569CB3"
cyan = "#6bd7d3"
green = "#0bb981"
magenta = "#8433fe"
red = "#e45451"
white = "#95917d"
yellow = "#fcc212"

[colors.primary]
background = "#1C1D22"
foreground = "#e1e7f5"
