#!/usr/bin/env bash
# script to start specific app on desktop start

# start steam
# steam &

# start solaar - logitech
solaar -w hide &

# start thunderbird using firejail
firejail --name=thunderbird --apparmor thunderbird %u &

# start vorta utility for borg backups
vorta -d &

# start aa-notify
bash ./launch-aanotify
