#!/usr/bin/env bash

# fuck that loud ass beep sound
xset -b &
xset b off &

# set german keyboard layout
# setxkbmap de &

# enable de_DE and en_US layout
# use ALT + SHIFT to switch between them
setxkbmap -layout de,us -option grp:alt_shift_toggle
